In [1]:
import numpy as np
from scipy import linalg

In [2]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [3]:
linalg.inv(A)

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [4]:
%%timeit

import numpy as np
from scipy import linalg
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
linalg.inv(A)

11.9 µs ± 208 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [5]:
a = list(range(1000000))

In [7]:
%%timeit
b = [c * c for c in a]

85.4 ms ± 1.05 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [8]:
A = np.array([[4, 2, 3], [4, 5, 6], [7, 8, 9]])

In [9]:
A

array([[4, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
linalg.inv(A)

array([[ 0.33333333, -0.66666667,  0.33333333],
       [-0.66666667, -1.66666667,  1.33333333],
       [ 0.33333333,  2.        , -1.33333333]])