In [1]:
import numpy as np

In [18]:
#создаём вектор из нулей

a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
#Размер массива

a.size * a.itemsize

80

In [20]:
#Нулевой массив размера 10 с 5ым элементом равным 1

a = np.zeros(10)
a[4] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [21]:
#Вектор со значениями от 10 до 49

a = np.arange(10, 50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [22]:
#Переворачиваем вектор

a = a[::-1]
a

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [23]:
#Создание матрицы 3 на 3 с элементами от 0 до 8

a = np.arange(0, 9).reshape(3, 3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [33]:
#Найти индексы ненулевых элементов

a = np.array([1,3,0,0,2,0])
b = np.nonzero(a)
b

(array([0, 1, 4], dtype=int64),)

In [36]:
#Создание единичной матрицы 3 на 3

b = np.eye(3)
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [45]:
#Создание 3 на 3 на 3 матрицы с рандомными значениями

c = np.random.random((3,3,3))
c

array([[[0.52783363, 0.08264606, 0.60837682],
        [0.85108253, 0.53769945, 0.59478658],
        [0.44142384, 0.52513645, 0.31099213]],

       [[0.55996695, 0.68512767, 0.77610414],
        [0.39239926, 0.15081271, 0.21459487],
        [0.12606833, 0.96381648, 0.63083113]],

       [[0.22863922, 0.31455163, 0.13564465],
        [0.66713652, 0.19298819, 0.6418251 ],
        [0.880689  , 0.71382612, 0.39405578]]])

In [49]:
c[1, 2, 2]

0.6308311318402766

In [59]:
#Массив 10x10 со случайными значениями и найдите минимальное и максимальное значения

c = np.random.randint(0, 10000, 100).reshape(10, 10)
c

array([[ 293, 5587,  256, 7470,   32, 4130, 1064, 1621, 5237, 9993],
       [8821, 8520, 4311, 3783, 3078,  569, 8637, 8549, 5808,  986],
       [9891, 9443, 2032, 2542, 2663, 4442, 7570, 9796, 2439,  891],
       [6698, 3410, 2164, 5044,  926, 3498, 2737, 6605,  948, 3508],
       [2387, 4787, 2185, 7158,  442, 8593, 9497, 3096, 3234, 5648],
       [5737, 3215, 2792, 7966, 2760,  889,  941, 4134, 4960, 9145],
       [9237, 5840,  833,  248, 9182, 6858,  759,  210, 4649, 6334],
       [4234, 8706, 4790, 2928, 1882, 4140, 1627,  784, 3390, 3343],
       [1212, 1068, 2312,  311, 7760, 4864, 2194, 9092, 8877,  892],
       [4682, 8500, 7430, 7978, 6611, 3077, 2384,  883, 5317, 9895]])

In [60]:
c.min()

32

In [61]:
c.max()

9993

In [62]:
#Создайте случайный вектор размером 30 и найдите среднее значение

c = np.random.rand(30)

In [63]:
c.mean()

0.5706442408744732

In [64]:
#Создайте 2d-массив с 1 на границе и 0 внутри

a = np.ones((10,10))
a[1:-1,1:-1] = 0
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])